In [1]:
import pandas as pd
import requests

In [15]:

url = "https://odds.p.rapidapi.com/v4/sports/upcoming/odds"

querystring = {"regions":"us","oddsFormat":"decimal","markets":"h2h,spreads","dateFormat":"iso"}

headers = {
	"x-rapidapi-key": "e06deac331mshe504ceb9a75df65p1620e8jsn991187b549e3",
	"x-rapidapi-host": "odds.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

[{'id': '2b94791c4f5079ae37c12fb8743e8967', 'sport_key': 'baseball_npb', 'sport_title': 'NPB', 'commence_time': '2026-04-12T04:00:00Z', 'home_team': 'Hokkaido Nippon-Ham Fighters', 'away_team': 'Fukuoka SoftBank Hawks', 'bookmakers': [{'key': 'fanduel', 'title': 'FanDuel', 'last_update': '2026-04-12T06:43:40Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 1.38}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 3.0}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 2.46, 'point': -1.5}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 1.52, 'point': 1.5}]}]}, {'key': 'fanatics', 'title': 'Fanatics', 'last_update': '2026-04-12T06:43:29Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:29Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 1.36}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 2.8}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:29Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 2.3, 'point': -1.5}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 1.53, 'point': 1.5}]}]}, {'key': 'mybookieag', 'title': 'MyBookie.ag', 'last_update': '2026-04-12T06:42:46Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:42:46Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 1.35}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 2.85}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:42:46Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 2.25, 'point': -1.5}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 1.6, 'point': 1.5}]}]}, {'key': 'williamhill_us', 'title': 'Caesars', 'last_update': '2026-04-12T06:43:10Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:10Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 1.45}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 2.65}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:10Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 2.3, 'point': -1.5}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 1.59, 'point': 1.5}]}]}, {'key': 'bovada', 'title': 'Bovada', 'last_update': '2026-04-12T06:38:35Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:38:35Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 1.42}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 2.8}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:38:35Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 2.45, 'point': -1.5}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 1.51, 'point': 1.5}]}]}, {'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2026-04-12T06:43:07Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:07Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 1.45}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 2.7}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:07Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 2.4, 'point': -1.5}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 1.56, 'point': 1.5}]}]}, {'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2026-04-12T06:42:59Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:42:59Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 1.45}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 2.55}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:42:59Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 2.6, 'point': -1.5}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 1.48, 'point': 1.5}]}]}, {'key': 'betrivers', 'title': 'BetRivers', 'last_update': '2026-04-12T06:43:18Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:18Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 1.38}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 2.85}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:18Z', 'outcomes': [{'name': 'Fukuoka SoftBank Hawks', 'price': 2.5, 'point': -1.5}, {'name': 'Hokkaido Nippon-Ham Fighters', 'price': 1.44, 'point': 1.5}]}]}]}, {'id': '7d362dde675c95816b7e5b1aecbc08bc', 'sport_key': 'baseball_npb', 'sport_title': 'NPB', 'commence_time': '2026-04-12T04:00:38Z', 'home_team': 'Saitama Seibu Lions', 'away_team': 'Chiba Lotte Marines', 'bookmakers': [{'key': 'fanatics', 'title': 'Fanatics', 'last_update': '2026-04-12T06:43:29Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:29Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 1.07}, {'name': 'Saitama Seibu Lions', 'price': 6.6}]}]}, {'key': 'fanduel', 'title': 'FanDuel', 'last_update': '2026-04-12T06:43:40Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 1.06}, {'name': 'Saitama Seibu Lions', 'price': 8.5}]}]}, {'key': 'mybookieag', 'title': 'MyBookie.ag', 'last_update': '2026-04-12T06:42:46Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:42:46Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 1.09}, {'name': 'Saitama Seibu Lions', 'price': 6.25}]}]}, {'key': 'williamhill_us', 'title': 'Caesars', 'last_update': '2026-04-12T06:43:10Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:10Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 1.1}, {'name': 'Saitama Seibu Lions', 'price': 6.5}]}]}, {'key': 'bovada', 'title': 'Bovada', 'last_update': '2026-04-12T06:33:51Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:33:51Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 1.09}, {'name': 'Saitama Seibu Lions', 'price': 7.0}]}]}, {'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2026-04-12T06:43:07Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:07Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 1.01}, {'name': 'Saitama Seibu Lions', 'price': 26.0}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:07Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 41.0, 'point': -1.5}, {'name': 'Saitama Seibu Lions', 'price': 1.0, 'point': 1.5}]}]}, {'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2026-04-12T06:42:59Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:42:59Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 1.14}, {'name': 'Saitama Seibu Lions', 'price': 5.0}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:42:59Z', 'outcomes': [{'name': 'Chiba Lotte Marines', 'price': 1.01, 'point': 1.5}, {'name': 'Saitama Seibu Lions', 'price': 21.0, 'point': -1.5}]}]}]}, {'id': '9e1204846a7cde287158c66a70837a81', 'sport_key': 'baseball_npb', 'sport_title': 'NPB', 'commence_time': '2026-04-12T04:01:00Z', 'home_team': 'Tohoku Rakuten Golden Eagles', 'away_team': 'Orix Buffaloes', 'bookmakers': [{'key': 'fanduel', 'title': 'FanDuel', 'last_update': '2026-04-12T06:43:40Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 4.2, 'point': 3.5}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 1.21, 'point': -3.5}]}]}, {'key': 'fanatics', 'title': 'Fanatics', 'last_update': '2026-04-12T06:43:29Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:43:29Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 3.8, 'point': 3.5}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 1.21, 'point': -3.5}]}]}, {'key': 'mybookieag', 'title': 'MyBookie.ag', 'last_update': '2026-04-12T06:42:46Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:42:46Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 1.3, 'point': 4.5}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 3.1, 'point': -4.5}]}]}, {'key': 'williamhill_us', 'title': 'Caesars', 'last_update': '2026-04-12T06:43:10Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:43:10Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 3.4, 'point': 3.5}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 1.29, 'point': -3.5}]}]}, {'key': 'bovada', 'title': 'Bovada', 'last_update': '2026-04-12T06:38:35Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:38:35Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 2.3, 'point': 4.0}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 1.57, 'point': -4.0}]}]}, {'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2026-04-12T06:43:07Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:43:07Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 4.1, 'point': 3.5}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 1.22, 'point': -3.5}]}]}, {'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2026-04-12T06:42:59Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:42:59Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 34.0}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 1.01}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:42:59Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 3.9, 'point': 3.5}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 1.24, 'point': -3.5}]}]}, {'key': 'betrivers', 'title': 'BetRivers', 'last_update': '2026-04-12T06:43:18Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:43:18Z', 'outcomes': [{'name': 'Orix Buffaloes', 'price': 3.35, 'point': 3.5}, {'name': 'Tohoku Rakuten Golden Eagles', 'price': 1.27, 'point': -3.5}]}]}]}, {'id': '4757fad7c2b15620ef60290efe811fd7', 'sport_key': 'baseball_npb', 'sport_title': 'NPB', 'commence_time': '2026-04-12T04:30:00Z', 'home_team': 'Chunichi Dragons', 'away_team': 'Hanshin Tigers', 'bookmakers': [{'key': 'fanatics', 'title': 'Fanatics', 'last_update': '2026-04-12T06:43:29Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:29Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 10.5}, {'name': 'Hanshin Tigers', 'price': 1.01}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:29Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 1.33, 'point': 3.5}, {'name': 'Hanshin Tigers', 'price': 3.0, 'point': -3.5}]}]}, {'key': 'fanduel', 'title': 'FanDuel', 'last_update': '2026-04-12T06:43:40Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 18.0}, {'name': 'Hanshin Tigers', 'price': 1.01}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 1.32, 'point': 3.5}, {'name': 'Hanshin Tigers', 'price': 3.25, 'point': -3.5}]}]}, {'key': 'mybookieag', 'title': 'MyBookie.ag', 'last_update': '2026-04-12T06:36:37Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:36:37Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 10.25}, {'name': 'Hanshin Tigers', 'price': 1.02}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:36:37Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 1.35, 'point': 3.5}, {'name': 'Hanshin Tigers', 'price': 2.95, 'point': -3.5}]}]}, {'key': 'williamhill_us', 'title': 'Caesars', 'last_update': '2026-04-12T06:43:10Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:10Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 13.0}, {'name': 'Hanshin Tigers', 'price': 1.01}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:10Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 1.38, 'point': 3.5}, {'name': 'Hanshin Tigers', 'price': 2.9, 'point': -3.5}]}]}, {'key': 'bovada', 'title': 'Bovada', 'last_update': '2026-04-12T06:36:13Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:36:13Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 13.0}, {'name': 'Hanshin Tigers', 'price': 1.03}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:36:13Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 1.71, 'point': 3.0}, {'name': 'Hanshin Tigers', 'price': 2.05, 'point': -3.0}]}]}, {'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2026-04-12T06:43:07Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:07Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 21.0}, {'name': 'Hanshin Tigers', 'price': 1.01}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:07Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 1.34, 'point': 3.5}, {'name': 'Hanshin Tigers', 'price': 3.2, 'point': -3.5}]}]}, {'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2026-04-12T06:42:59Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:42:59Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 21.0}, {'name': 'Hanshin Tigers', 'price': 1.01}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:42:59Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 1.4, 'point': 3.5}, {'name': 'Hanshin Tigers', 'price': 2.9, 'point': -3.5}]}]}, {'key': 'betrivers', 'title': 'BetRivers', 'last_update': '2026-04-12T06:43:18Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:43:18Z', 'outcomes': [{'name': 'Chunichi Dragons', 'price': 1.29, 'point': 3.5}, {'name': 'Hanshin Tigers', 'price': 3.15, 'point': -3.5}]}]}]}, {'id': '52708363a1e28435c9d0d14ee7f9634a', 'sport_key': 'soccer_korea_kleague1', 'sport_title': 'K League 1', 'commence_time': '2026-04-12T05:00:00Z', 'home_team': 'Daejeon Citizen', 'away_team': 'Gangwon FC', 'bookmakers': [{'key': 'fanatics', 'title': 'Fanatics', 'last_update': '2026-04-12T06:43:26Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:26Z', 'outcomes': [{'name': 'Daejeon Citizen', 'price': 71.0}, {'name': 'Gangwon FC', 'price': 1.1}, {'name': 'Draw', 'price': 6.0}]}]}, {'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2026-04-12T06:43:38Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:38Z', 'outcomes': [{'name': 'Daejeon Citizen', 'price': 91.0}, {'name': 'Gangwon FC', 'price': 1.11}, {'name': 'Draw', 'price': 6.0}]}]}, {'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2026-04-12T06:32:06Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:32:06Z', 'outcomes': [{'name': 'Daejeon Citizen', 'price': 20.0}, {'name': 'Gangwon FC', 'price': 1.2}, {'name': 'Draw', 'price': 4.5}]}]}]}, {'id': '2c37dedd39c2f77315173fa0a43c82b4', 'sport_key': 'soccer_australia_aleague', 'sport_title': 'A-League', 'commence_time': '2026-04-12T05:00:00Z', 'home_team': 'Melbourne City', 'away_team': 'Wellington Phoenix FC', 'bookmakers': [{'key': 'fanatics', 'title': 'Fanatics', 'last_update': '2026-04-12T06:43:12Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:12Z', 'outcomes': [{'name': 'Melbourne City', 'price': 1.0}, {'name': 'Wellington Phoenix FC', 'price': 901.0}, {'name': 'Draw', 'price': 51.0}]}]}, {'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2026-04-12T06:33:19Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:33:19Z', 'outcomes': [{'name': 'Melbourne City', 'price': 1.15}, {'name': 'Wellington Phoenix FC', 'price': 23.0}, {'name': 'Draw', 'price': 5.5}]}]}, {'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2026-04-12T06:34:11Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:34:11Z', 'outcomes': [{'name': 'Melbourne City', 'price': 1.17}, {'name': 'Wellington Phoenix FC', 'price': 31.0}, {'name': 'Draw', 'price': 5.25}]}]}, {'key': 'bovada', 'title': 'Bovada', 'last_update': '2026-04-12T06:31:40Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:31:40Z', 'outcomes': [{'name': 'Melbourne City', 'price': 1.2}, {'name': 'Wellington Phoenix FC', 'price': 23.0}, {'name': 'Draw', 'price': 5.5}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:31:40Z', 'outcomes': [{'name': 'Melbourne City', 'price': 2.28, 'point': -1.25}, {'name': 'Wellington Phoenix FC', 'price': 1.65, 'point': 1.25}]}]}]}, {'id': '5c4f81722587ee3067bca2bbf336c5c6', 'sport_key': 'soccer_japan_j_league', 'sport_title': 'J League', 'commence_time': '2026-04-12T05:00:00Z', 'home_team': 'Urawa Red Diamonds', 'away_team': 'Tokyo Verdy', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2026-04-12T06:35:39Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:35:39Z', 'outcomes': [{'name': 'Tokyo Verdy', 'price': 5.25}, {'name': 'Urawa Red Diamonds', 'price': 3.6}, {'name': 'Draw', 'price': 1.53}]}]}, {'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2026-04-12T06:43:14Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:14Z', 'outcomes': [{'name': 'Tokyo Verdy', 'price': 7.5}, {'name': 'Urawa Red Diamonds', 'price': 4.9}, {'name': 'Draw', 'price': 1.36}]}]}]}, {'id': 'c9a24e7b9068cfe1d5516389bef82be7', 'sport_key': 'baseball_kbo', 'sport_title': 'KBO', 'commence_time': '2026-04-12T05:00:28Z', 'home_team': 'Hanwha Eagles', 'away_team': 'Kia Tigers', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2026-04-12T06:38:56Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:38:56Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 4.75}, {'name': 'Kia Tigers', 'price': 1.16}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:38:56Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 1.74, 'point': 3.0}, {'name': 'Kia Tigers', 'price': 2.0, 'point': -3.0}]}]}, {'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2026-04-12T06:43:40Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 3.0}, {'name': 'Kia Tigers', 'price': 1.37}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 2.05, 'point': 1.5}, {'name': 'Kia Tigers', 'price': 1.74, 'point': -1.5}]}]}, {'key': 'mybookieag', 'title': 'MyBookie.ag', 'last_update': '2026-04-12T06:42:56Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:42:56Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 4.35}, {'name': 'Kia Tigers', 'price': 1.18}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:42:56Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 2.0, 'point': 2.5}, {'name': 'Kia Tigers', 'price': 1.75, 'point': -2.5}]}]}, {'key': 'fanduel', 'title': 'FanDuel', 'last_update': '2026-04-12T06:43:29Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:29Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 3.3}, {'name': 'Kia Tigers', 'price': 1.32}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:29Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 2.02, 'point': 1.5}, {'name': 'Kia Tigers', 'price': 1.76, 'point': -1.5}]}]}, {'key': 'fanatics', 'title': 'Fanatics', 'last_update': '2026-04-12T06:43:18Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:18Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 3.05}, {'name': 'Kia Tigers', 'price': 1.31}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:18Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 2.0, 'point': 1.5}, {'name': 'Kia Tigers', 'price': 1.71, 'point': -1.5}]}]}, {'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2026-04-12T06:43:40Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 3.1}, {'name': 'Kia Tigers', 'price': 1.35}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:43:40Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 2.05, 'point': 1.5}, {'name': 'Kia Tigers', 'price': 1.74, 'point': -1.5}]}]}, {'key': 'williamhill_us', 'title': 'Caesars', 'last_update': '2026-04-12T06:42:36Z', 'markets': [{'key': 'h2h', 'last_update': '2026-04-12T06:42:36Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 3.1}, {'name': 'Kia Tigers', 'price': 1.33}]}, {'key': 'spreads', 'last_update': '2026-04-12T06:42:36Z', 'outcomes': [{'name': 'Hanwha Eagles', 'price': 2.05, 'point': 1.5}, {'name': 'Kia Tigers', 'price': 1.74, 'point': -1.5}]}]}]}, {'id': '0db745dff1223d606a660cd512e7808f', 'sport_key': 'baseball_kbo', 'sport_title': 'KBO', 'commence_time': '2026-04-12T05:00:41Z', 'home_team': 'LG Twins', 'away_team': 'SSG Landers', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2026-04-12T06:36:26Z', 'markets': [{'key': 'spreads', 'last_update': '2026-04-12T06:36:26Z', 'outcomes': [{'name': 'LG Twins', 'price': 1.8, 'point': -4.0}, {'name': 'SSG Landers', 'price': 1.95, 'point': 4.0}]}]}, {'key': 'draftkings', 'title': 'Draf

In [16]:
data = response.json()

temp_df = pd.DataFrame([{
    
    # match info
    'sport_key': match.get('sport_key'),
    'commence_time': match.get('commence_time'),
    'home_team': match.get('home_team'),
    'away_team': match.get('away_team'),
    
    # 🔥 best odds (from all bookmakers)
    'home_team_odds': min([
        outcome['price']
        for bookmaker in match.get('bookmakers', [])
        for market in bookmaker.get('markets', [])
        if market.get('key') == 'h2h'
        for outcome in market.get('outcomes', [])
        if outcome.get('name') == match.get('home_team')
    ], default=None),
    
    'away_team_odds': min([
        outcome['price']
        for bookmaker in match.get('bookmakers', [])
        for market in bookmaker.get('markets', [])
        if market.get('key') == 'h2h'
        for outcome in market.get('outcomes', [])
        if outcome.get('name') == match.get('away_team')
    ], default=None),
    
   
    'home_point': next((
        outcome.get('point')
        for bookmaker in match.get('bookmakers', [])
        for market in bookmaker.get('markets', [])
        if market.get('key') == 'spreads'
        for outcome in market.get('outcomes', [])
        if outcome.get('name') == match.get('home_team')
    ), None),
    
    'away_point': next((
        outcome.get('point')
        for bookmaker in match.get('bookmakers', [])
        for market in bookmaker.get('markets', [])
        if market.get('key') == 'spreads'
        for outcome in market.get('outcomes', [])
        if outcome.get('name') == match.get('away_team')
    ), None),

} for match in data])

print(temp_df.head())

               sport_key         commence_time                     home_team  \
0           baseball_npb  2026-04-12T04:00:00Z  Hokkaido Nippon-Ham Fighters
1           baseball_npb  2026-04-12T04:00:38Z           Saitama Seibu Lions
2           baseball_npb  2026-04-12T04:01:00Z  Tohoku Rakuten Golden Eagles
3           baseball_npb  2026-04-12T04:30:00Z              Chunichi Dragons
4  soccer_korea_kleague1  2026-04-12T05:00:00Z               Daejeon Citizen

                away_team  home_team_odds  away_team_odds  home_point  \
0  Fukuoka SoftBank Hawks            2.55            1.35         1.5
1     Chiba Lotte Marines            5.00            1.01         1.5
2          Orix Buffaloes            1.01           34.00        -3.5
3          Hanshin Tigers           10.25            1.01         3.5
4              Gangwon FC           20.00            1.10         NaN

   away_point
0        -1.5
1        -1.5
2         3.5
3        -3.5
4         NaN

In [18]:
temp_df

,sport_key,commence_time,home_team,away_team,home_team_odds,away_team_odds,home_point,away_point
0,baseball_npb,2026-04-12T04:00:00Z,Hokkaido Nippon-Ham Fighters,Fukuoka SoftBank Hawks,2.55,1.35,1.50,-1.50
1,baseball_npb,2026-04-12T04:00:38Z,Saitama Seibu Lions,Chiba Lotte Marines,5.00,1.01,1.50,-1.50
2,baseball_npb,2026-04-12T04:01:00Z,Tohoku Rakuten Golden Eagles,Orix Buffaloes,1.01,34.00,-3.50,3.50
3,baseball_npb,2026-04-12T04:30:00Z,Chunichi Dragons,Hanshin Tigers,10.25,1.01,3.50,-3.50
4,soccer_korea_kleague1,2026-04-12T05:00:00Z,Daejeon Citizen,Gangwon FC,20.00,1.10,NaN,NaN
5,soccer_australia_aleague,2026-04-12T05:00:00Z,Melbourne City,Wellington Phoenix FC,1.00,23.00,-1.25,1.25
6,soccer_japan_j_league,2026-04-12T05:00:00Z,Urawa Red Diamonds,Tokyo Verdy,3.60,5.25,NaN,NaN
7,baseball_kbo,2026-04-12T05:00:28Z,Hanwha Eagles,Kia Tigers,3.00,1.16,3.00,-3.00
8,baseball_kbo,2026-04-12T05:00:41Z,LG Twins,SSG Landers,1.01,9.50,-4.00,4.00
9,baseball_kbo,2026-04-12T05:00:46Z,KT Wiz,Doosan Bears,1.03,6.25,-3.00,3.00
10,baseball_npb,2026-04-12T05:00:57Z,Yokohama DeNA BayStars,Hiroshima Toyo Carp,3.80,1.17,1.50,-1.50
11,baseball_npb,2026-04-12T05:00:58Z,Yomiuri Giants,Tokyo Yakult Swallows,4.55,1.12,1.50,-1.50
12,baseball_kbo,2026-04-12T05:01:06Z,Kiwoom Heroes,Lotte Giants,1.10,5.10,-2.00,2.00
13,baseball_kbo,2026-04-12T05:01:07Z,Samsung Lions,NC Dinos,1.00,11.00,-5.50,5.50
14,rugbyleague_nrl,2026-04-12T06:05:00Z,Wests Tigers,Newcastle Knights,NaN,NaN,-13.50,13.50
15,soccer_japan_j_league,2026-04-12T07:00:00Z,Kawasaki Frontale,Kashima Antlers,2.95,2.25,NaN,NaN
16,soccer_korea_kleague1,2026-04-12T07:30:00Z,Sangju Sangmu FC,FC Anyang,2.28,2.75,0.00,0.00
17,soccer_australia_aleague,2026-04-12T09:00:00Z,Perth Glory,Macarthur FC,3.00,2.12,0.25,-0.25
18,aussierules_afl,2026-04-12T09:15:00Z,Port Adelaide Power,St Kilda Saints,2.20,1.65,6.50,-6.50
19,cricket_ipl,2026-04-12T10:00:00Z,Lucknow Super Giants,Gujarat Titans,2.00,1.77,NaN,NaN
20,soccer_poland_ekstraklasa,2026-04-12T10:15:00Z,Cracovia Kraków,Arka Gdynia,1.92,3.60,-0.50,0.50
21,soccer_netherlands_eredivisie,2026-04-12T10:15:00Z,Fortuna Sittard,NAC Breda,2.80,2.30,0.00,0.00
22,soccer_italy_serie_a,2026-04-12T10:30:00Z,Genoa,Sassuolo,2.07,3.50,-0.25,0.25

In [19]:
df = pd.DataFrame()

In [20]:

df = pd.concat([df, temp_df], ignore_index=True)

In [21]:
df.head()

,sport_key,commence_time,home_team,away_team,home_team_odds,away_team_odds,home_point,away_point
0,baseball_npb,2026-04-12T04:00:00Z,Hokkaido Nippon-Ham Fighters,Fukuoka SoftBank Hawks,2.55,1.35,1.5,-1.5
1,baseball_npb,2026-04-12T04:00:38Z,Saitama Seibu Lions,Chiba Lotte Marines,5.00,1.01,1.5,-1.5
2,baseball_npb,2026-04-12T04:01:00Z,Tohoku Rakuten Golden Eagles,Orix Buffaloes,1.01,34.00,-3.5,3.5
3,baseball_npb,2026-04-12T04:30:00Z,Chunichi Dragons,Hanshin Tigers,10.25,1.01,3.5,-3.5
4,soccer_korea_kleague1,2026-04-12T05:00:00Z,Daejeon Citizen,Gangwon FC,20.00,1.10,NaN,NaN

In [22]:
df.shape

(23, 8)

In [24]:
df.to_csv('theoddsAPI.csv')